### ISSUE TITLE
Feature request: sixel graphics

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/classy#6]
HI Max,

I like to work with the terminal and often over ssh. Especially with the latter, it means I cannot trivially get pretty plots of asteroid spectra.
My terminal of choice supports displaying graphics on the terminal (including over ssh!) through the sixel protocol, and I would love to have the ability to display graphics that way. I see you use matplotlib for creating these plots which has a sixel backend available, so I think in theory it should be easy to set up. If you want and think this is something you wouldn't mind having, I can see if I can hack something together on that front myself also.

Cheers,
Lauri

**Comment by maxmahlke** [comment]
Hi Lauri,

overall, the `classy spectra` interface is open for input. For now, it opens a matplotlib plot because I frequently want to plot spectra, but there are certainly more use cases we can include. I've been thinking e.g. that `classy spectra ceres` should just print a table of available spectra of Ceres + metadata, while the matplotlib interface should only open if a `--plot` flag is given.

So, yes, if you can make a working prototype of what you are looking for I'd be happy to include it! Your prototype does not need to work around `classy` yet, just some way to show how you would plot via sixel.

Cheers

**Comment by Siltala** [comment]
Actually, this is even simpler than I thought and doesn't even need any changes to classy's code - with the `matplotlib-sixel` package installed it is just a matter of editing the `matplotlibrc` file to use the relevant backend. Here is a random screenshot of me running classy on a remote server over ssh! Clearly the colors are a bit off (and the figure was very small, I had to zoom the terminal a lot) but I think that these are not classy's fault and I will see if I can improve the situation there (through further changes in  matplotlibrc perhaps?)

![image](https://github.com/maxmahlke/classy/assets/2873449/9230c32b-a517-4a30-96ef-fe68f83c1c64)

**Comment by Siltala** [comment]
Much, much better with the `matplotlib-sixel`backend itself edited to not use transparency (which I think sixel graphics don't really support anyway). Now it does exactly what I want, so I guess I solved my own problem here. :)

![image](https://github.com/maxmahlke/classy/assets/2873449/7fb87956-25b8-470b-80bb-3522bdd00355)

**Comment by maxmahlke** [comment]
Great! I didn't know about this backend, it looks very useful.

Btw sine I myself have a custom `matplotlib` rc file, `classy` resets the ` rc parameters when plotting spectra:

https://github.com/maxmahlke/classy/blob/31b4e93385ad51eba06be5d31455e79d644435bb/classy/plotting.py#L310

This might confuse you at some point so I'm pointing it out here.
